version: '3'

services:

  mysql-local:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shortener
      - MYSQL_USER=springstudent
      - MYSQL_PASSWORD=springstudent
    ports:
      - 3306:3306

  myapp-main:
    build:
      context: .
      dockerfile: Dockerfile
    image: amarin/url-shortener
    restart: on-failure
    depends_on:
      - localhost ##can be changed to mysql-local
    ports:
      - 8158:8158
      